custom:  # 自定义http启动端口
  http-port: 8089
  wx:
    app-id: wx14bef30eef2d69c5
    secret: 135442bf268031dade07929a3a445f4c
    url: https://api.weixin.qq.com/sns/jscode2session
  dy:
    app-id: tt8234f4891d03380f01
    secret: 18812aa4a7da31e0dea94c596569cced0d719fb6
    url: https://open-sandbox.douyin.com/api/apps/v2/jscode2session
#    url: https://developer.toutiao.com/api/apps/v2/jscode2session
server:
  port: 8081
  ssl:
    key-store-password: 390wyewee1zcd
    key-store-type: JKS
    key-store: classpath:shanghaikomo.com.jks
    enabled: true


# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-1b3qrsfi.sql.tencentcdb.com:27312/komo?setUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://sh-cdb-7306a6p8.sql.tencentcdb.com:24421/komo?setUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://sh-cdb-0i7s05z6.sql.tencentcdb.com:26077/komo?setUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://127.0.0.1:3306/komo?setUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: zhw121110
#    password: 121110
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 60
      # 链接超时时间，默认 30000(30 秒)
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认 600000(10 分钟)
      idle-timeout: 60000
      # 连接将被测试活动的最大时间量
      validation-timeout: 3000
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000(30 分钟)
      max-lifetime: 60000
      # 连接到数据库时等待的最长时间(秒)
      login-timeout: 5
      # 池中维护的最小空闲连接数
      minimum-idle: 10
  data:
    redis:
      host: 124.222.74.122
      port: 6379
      password: zhw121110

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.komo.server.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义SQL注入器
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    #springboot 项目mybatis plus 设置 jdbcTypeForNull (oracle数据库需配置JdbcType.NULL, 默认是Other)
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志